version: '3.8'

services:
  db:
    image: postgres:16       
    container_name: linkvault-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: zainab
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: linkvault
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata: